//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientConsumerService.ComisionCalculatorProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ComisionCalculatorProxy.IComisionCalculator")]
    public interface IComisionCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComisionCalculator/CalculateFee", ReplyAction="http://tempuri.org/IComisionCalculator/CalculateFeeResponse")]
        decimal CalculateFee(decimal price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComisionCalculator/CalculateFee", ReplyAction="http://tempuri.org/IComisionCalculator/CalculateFeeResponse")]
        System.Threading.Tasks.Task<decimal> CalculateFeeAsync(decimal price);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComisionCalculatorChannel : ClientConsumerService.ComisionCalculatorProxy.IComisionCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComisionCalculatorClient : System.ServiceModel.ClientBase<ClientConsumerService.ComisionCalculatorProxy.IComisionCalculator>, ClientConsumerService.ComisionCalculatorProxy.IComisionCalculator {
        
        public ComisionCalculatorClient() {
        }
        
        public ComisionCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComisionCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComisionCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComisionCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal CalculateFee(decimal price) {
            return base.Channel.CalculateFee(price);
        }
        
        public System.Threading.Tasks.Task<decimal> CalculateFeeAsync(decimal price) {
            return base.Channel.CalculateFeeAsync(price);
        }
    }
}
